services:
    whatsupdocker:
        image: getwud/wud
        container_name: wud
        volumes:
            - ${XDG_RUNTIME_DIR}/podman/podman.sock:/var/run/docker.sock
        ports:
            - "${WUD_PORT}:3000"
